name: build
on:
  pull_request:
    paths:
      - "**"
  push:
    branches:
      - master

jobs:
  android:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.0
        with:
          flutter-version: '1.21.0-9.0.pre'
          channel: 'dev' 
      - name: Install Dependencies
        run: flutter packages get
      - name: Build example
        run: |
             cd example
             flutter build apk

